/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.jpanel;

import controller.FacadeHost;
import controller.Host;
import interfaces.Base;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultListModel;
import moduledefault.clustering.view.jpanel.PanelFormigas;

/**
 *
 * @author Mateusinho
 */
public class BackupClustering extends javax.swing.JPanel implements Observer {
    
    private ArrayList<Base> arrayListBases = new ArrayList<>(); //LISTA DE BASE DE DADOS

    /**
     * Creates new form JPanelClustering
     */
    public BackupClustering()  {
        FacadeHost.getHost().addObserver(this);
        initComponents();
        jButtonAgrupar.setEnabled(true);
        jButtonConfiguracao.setEnabled(false);
        jButtonRecuperacao.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDistancias = new javax.swing.ButtonGroup();
        grupoRec = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPaneRunning = new javax.swing.JScrollPane();
        jListResult = new javax.swing.JList();
        jScrollPaneResult1 = new javax.swing.JScrollPane();
        jListResult1 = new javax.swing.JList();
        jPanelMedidas = new javax.swing.JPanel();
        opChebyshev = new javax.swing.JRadioButton();
        opCityBlock = new javax.swing.JRadioButton();
        opCorrelacao = new javax.swing.JRadioButton();
        opCosseno = new javax.swing.JRadioButton();
        opEuclidiana = new javax.swing.JRadioButton();
        opMahalanobis = new javax.swing.JRadioButton();
        jButtonAgrupar = new javax.swing.JButton();
        jButtonRecuperacao = new javax.swing.JButton();
        jPanelMedidas1 = new javax.swing.JPanel();
        opLigCompleta = new javax.swing.JRadioButton();
        opLigSimples = new javax.swing.JRadioButton();
        opLigMedia = new javax.swing.JRadioButton();
        opFaino = new javax.swing.JRadioButton();
        opWard = new javax.swing.JRadioButton();
        jComboBoxMetodos = new javax.swing.JComboBox();
        jButtonConfiguracao = new javax.swing.JButton();
        jLabelMetodosDisponiveis = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(666, 499));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tarefa de Agrupamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 18))); // NOI18N

        jScrollPaneRunning.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPaneRunning.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jListResult.setModel(new DefaultListModel());
        jListResult.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListResultMouseClicked(evt);
            }
        });
        jListResult.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jListResultKeyReleased(evt);
            }
        });
        jScrollPaneRunning.setViewportView(jListResult);

        jScrollPaneResult1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Resultados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N

        jListResult1.setModel(new DefaultListModel());
        jListResult1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListResult1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListResult1MouseClicked(evt);
            }
        });
        jListResult1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jListResult1KeyReleased(evt);
            }
        });
        jScrollPaneResult1.setViewportView(jListResult1);

        jPanelMedidas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Medidas de Distância", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12), java.awt.Color.black)); // NOI18N

        grupoDistancias.add(opChebyshev);
        opChebyshev.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        opChebyshev.setSelected(true);
        opChebyshev.setText("Chebyshev");

        grupoDistancias.add(opCityBlock);
        opCityBlock.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        opCityBlock.setText("CityBlock");

        grupoDistancias.add(opCorrelacao);
        opCorrelacao.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        opCorrelacao.setText("Correlação");

        grupoDistancias.add(opCosseno);
        opCosseno.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        opCosseno.setText("Cosseno");

        grupoDistancias.add(opEuclidiana);
        opEuclidiana.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        opEuclidiana.setText("Euclidiana");

        grupoDistancias.add(opMahalanobis);
        opMahalanobis.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        opMahalanobis.setText("Mahalanobis");

        javax.swing.GroupLayout jPanelMedidasLayout = new javax.swing.GroupLayout(jPanelMedidas);
        jPanelMedidas.setLayout(jPanelMedidasLayout);
        jPanelMedidasLayout.setHorizontalGroup(
            jPanelMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMedidasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opEuclidiana)
                    .addComponent(opChebyshev)
                    .addComponent(opCityBlock)
                    .addComponent(opCorrelacao)
                    .addComponent(opCosseno)
                    .addComponent(opMahalanobis))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMedidasLayout.setVerticalGroup(
            jPanelMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMedidasLayout.createSequentialGroup()
                .addComponent(opChebyshev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opCityBlock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opCorrelacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opCosseno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opEuclidiana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opMahalanobis)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jButtonAgrupar.setText("Agrupar");
        jButtonAgrupar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgruparActionPerformed(evt);
            }
        });

        jButtonRecuperacao.setText("Recuperar Grupos");

        jPanelMedidas1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Recuperação de Grupos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12), java.awt.Color.black)); // NOI18N

        grupoRec.add(opLigCompleta);
        opLigCompleta.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        opLigCompleta.setSelected(true);
        opLigCompleta.setText("Ligação Completa");

        grupoRec.add(opLigSimples);
        opLigSimples.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        opLigSimples.setText("Ligação Simples");

        grupoRec.add(opLigMedia);
        opLigMedia.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        opLigMedia.setText("Ligação Média");

        grupoRec.add(opFaino);
        opFaino.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        opFaino.setText("Método Faino");

        grupoRec.add(opWard);
        opWard.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        opWard.setText("Método de Ward");
        opWard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opWardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMedidas1Layout = new javax.swing.GroupLayout(jPanelMedidas1);
        jPanelMedidas1.setLayout(jPanelMedidas1Layout);
        jPanelMedidas1Layout.setHorizontalGroup(
            jPanelMedidas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMedidas1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMedidas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opWard)
                    .addComponent(opLigCompleta)
                    .addComponent(opLigSimples)
                    .addComponent(opLigMedia)
                    .addComponent(opFaino))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanelMedidas1Layout.setVerticalGroup(
            jPanelMedidas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMedidas1Layout.createSequentialGroup()
                .addComponent(opLigCompleta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opLigSimples)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opLigMedia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opFaino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opWard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jComboBoxMetodos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Colônia de Fomigas", "K-means", "Self-Organizing Map (SOM) ", "Ligação Simples", "Ligação Média", "Ligação Completa", "Ward" }));
        jComboBoxMetodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMetodosActionPerformed(evt);
            }
        });

        jButtonConfiguracao.setText("Configurações");
        jButtonConfiguracao.setEnabled(false);

        jLabelMetodosDisponiveis.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabelMetodosDisponiveis.setText("Métodos Disponíveis:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPaneResult1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanelMedidas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelMedidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 220, Short.MAX_VALUE)
                                .addComponent(jButtonAgrupar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRecuperacao))
                            .addComponent(jScrollPaneRunning)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMetodosDisponiveis)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jComboBoxMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonConfiguracao)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelMetodosDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConfiguracao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPaneRunning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAgrupar)
                            .addComponent(jButtonRecuperacao)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanelMedidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelMedidas1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneResult1, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jListResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListResultMouseClicked
        //        if (evt.getClickCount() == 2)
//        jListResultActionPerformed();
    }//GEN-LAST:event_jListResultMouseClicked

    private void jListResultKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jListResultKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_UP
                || evt.getKeyCode() == KeyEvent.VK_DOWN
                || evt.getKeyCode() == KeyEvent.VK_PAGE_DOWN
                || evt.getKeyCode() == KeyEvent.VK_PAGE_UP
                || evt.getKeyCode() == KeyEvent.VK_END
                || evt.getKeyCode() == KeyEvent.VK_HOME) {
//            jListResultActionPerformed();
        }
    }//GEN-LAST:event_jListResultKeyReleased

    private void jListResult1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListResult1MouseClicked
        //        if (evt.getClickCount() == 2)
//        jListResultActionPerformed();
    }//GEN-LAST:event_jListResult1MouseClicked

    private void jListResult1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jListResult1KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_UP
                || evt.getKeyCode() == KeyEvent.VK_DOWN
                || evt.getKeyCode() == KeyEvent.VK_PAGE_DOWN
                || evt.getKeyCode() == KeyEvent.VK_PAGE_UP
                || evt.getKeyCode() == KeyEvent.VK_END
                || evt.getKeyCode() == KeyEvent.VK_HOME) {
//            jListResultActionPerformed();
        }
    }//GEN-LAST:event_jListResult1KeyReleased

    private void jComboBoxMetodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMetodosActionPerformed
        if (jComboBoxMetodos.getSelectedIndex() == 0) {
            jButtonConfiguracao.setEnabled(false);
        } else {
            jButtonConfiguracao.setEnabled(true);
        }
        if (jComboBoxMetodos.getSelectedIndex() == 1) { //Colônia de Fomigas
            //
           // PanelFormigas formigas = new PanelFormigas();
          //  formigas.setSize(100, 100);
           // jPanel2.add(formigas);
        }
        if (jComboBoxMetodos.getSelectedIndex() == 2) { //K-means
            //
        } 
        if (jComboBoxMetodos.getSelectedIndex() == 3) { //Kohonen
            //
        } 
        if (jComboBoxMetodos.getSelectedIndex() == 4) { //Ligação Simples
            //
        } 
        if (jComboBoxMetodos.getSelectedIndex() == 4) { //Ligação Simples
            //
        } 
        if (jComboBoxMetodos.getSelectedIndex() == 5) { //Ligação Completa
            //
        } 
        if (jComboBoxMetodos.getSelectedIndex() == 6) { //Ward
            //
        } 
    }//GEN-LAST:event_jComboBoxMetodosActionPerformed

    private void jButtonAgruparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgruparActionPerformed
        //IMPRIMO A BASE
        
        System.out.println(arrayListBases.size());
        
        for (int i = 0; i < arrayListBases.get(0).getInput().length; i++) {
            for (int j = 0; j < arrayListBases.get(0).getInput()[0].length; j++) {
            System.out.print(arrayListBases.get(0).getInput()[i][j]+" ");
            }
            System.out.println("");
        }
    }//GEN-LAST:event_jButtonAgruparActionPerformed

    private void opWardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opWardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opWardActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoDistancias;
    private javax.swing.ButtonGroup grupoRec;
    private javax.swing.JButton jButtonAgrupar;
    private javax.swing.JButton jButtonConfiguracao;
    private javax.swing.JButton jButtonRecuperacao;
    private javax.swing.JComboBox jComboBoxMetodos;
    private javax.swing.JLabel jLabelMetodosDisponiveis;
    private javax.swing.JList jListResult;
    private javax.swing.JList jListResult1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelMedidas;
    private javax.swing.JPanel jPanelMedidas1;
    private javax.swing.JScrollPane jScrollPaneResult1;
    private javax.swing.JScrollPane jScrollPaneRunning;
    private javax.swing.JRadioButton opChebyshev;
    private javax.swing.JRadioButton opCityBlock;
    private javax.swing.JRadioButton opCorrelacao;
    private javax.swing.JRadioButton opCosseno;
    private javax.swing.JRadioButton opEuclidiana;
    private javax.swing.JRadioButton opFaino;
    private javax.swing.JRadioButton opLigCompleta;
    private javax.swing.JRadioButton opLigMedia;
    private javax.swing.JRadioButton opLigSimples;
    private javax.swing.JRadioButton opMahalanobis;
    private javax.swing.JRadioButton opWard;
    // End of variables declaration//GEN-END:variables

 public void update(Observable o, Object o1) {
        if (o instanceof Host) {
            if ((o1 instanceof Base) && ((Base) o1).hasMeta()) {
                arrayListBases.add((Base) o1); //PEGO A BASE
            }
        }
    }
}
