/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package moduledefault.clustering.view.jpanel;

import java.awt.event.KeyEvent;
import javax.swing.DefaultListModel;

/**
 *
 * @author Mateus
 */
public class PanelHierarquicos extends javax.swing.JPanel {

    /**
     * Creates new form PanelHierarquicos
     */
    public PanelHierarquicos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_medidas = new javax.swing.JPanel();
        Euclidiana = new javax.swing.JRadioButton();
        Cosseno = new javax.swing.JRadioButton();
        Mahalanobis = new javax.swing.JRadioButton();
        Correlacao = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        ligaSimples = new javax.swing.JRadioButton();
        ligaCompleta = new javax.swing.JRadioButton();
        ligaMedia = new javax.swing.JRadioButton();
        ligaWard = new javax.swing.JRadioButton();
        jScrollPaneResult = new javax.swing.JScrollPane();
        jListResult = new javax.swing.JList();
        buttonExecutar = new javax.swing.JButton();
        buttonTela = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(718, 458));

        Panel_medidas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Medidas"));

        Euclidiana.setText("Distância Euclidiana");
        Euclidiana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EuclidianaActionPerformed(evt);
            }
        });

        Cosseno.setText("Similiridade de Cosseno");
        Cosseno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CossenoActionPerformed(evt);
            }
        });

        Mahalanobis.setText("Mahalanobis");
        Mahalanobis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MahalanobisActionPerformed(evt);
            }
        });

        Correlacao.setText("Correlação");
        Correlacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorrelacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_medidasLayout = new javax.swing.GroupLayout(Panel_medidas);
        Panel_medidas.setLayout(Panel_medidasLayout);
        Panel_medidasLayout.setHorizontalGroup(
            Panel_medidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_medidasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_medidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cosseno)
                    .addComponent(Euclidiana)
                    .addComponent(Mahalanobis)
                    .addComponent(Correlacao)))
        );
        Panel_medidasLayout.setVerticalGroup(
            Panel_medidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_medidasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Euclidiana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cosseno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Mahalanobis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Correlacao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Métodos"));

        ligaSimples.setText("Ligação Simples");
        ligaSimples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ligaSimplesActionPerformed(evt);
            }
        });

        ligaCompleta.setText("Ligação Completa");
        ligaCompleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ligaCompletaActionPerformed(evt);
            }
        });

        ligaMedia.setText("Ligação Média");
        ligaMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ligaMediaActionPerformed(evt);
            }
        });

        ligaWard.setText("Ward");
        ligaWard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ligaWardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ligaCompleta)
                    .addComponent(ligaSimples)
                    .addComponent(ligaMedia)
                    .addComponent(ligaWard))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ligaSimples)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ligaCompleta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ligaMedia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ligaWard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPaneResult.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Resultados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N

        jListResult.setModel(new DefaultListModel());
        jListResult.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListResultMouseClicked(evt);
            }
        });
        jListResult.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jListResultKeyReleased(evt);
            }
        });
        jScrollPaneResult.setViewportView(jListResult);

        buttonExecutar.setText("Executar");

        buttonTela.setText("Limpar Tela");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneResult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel_medidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonExecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTela, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Panel_medidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonExecutar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonTela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneResult, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EuclidianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EuclidianaActionPerformed
        if (Euclidiana.isSelected()) {
            Correlacao.setEnabled(false);
            Cosseno.setEnabled(false);
            Mahalanobis.setEnabled(false);
        } else {
            Correlacao.setEnabled(true);
            Cosseno.setEnabled(true);
            Mahalanobis.setEnabled(true);
        }
    }//GEN-LAST:event_EuclidianaActionPerformed

    private void CossenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CossenoActionPerformed
        if (Cosseno.isSelected()) {
            Euclidiana.setEnabled(false);
            Correlacao.setEnabled(false);
            Mahalanobis.setEnabled(false);
        } else {
            Euclidiana.setEnabled(true);
            Correlacao.setEnabled(true);
            Mahalanobis.setEnabled(true);
        }
    }//GEN-LAST:event_CossenoActionPerformed

    private void MahalanobisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MahalanobisActionPerformed
        if (Mahalanobis.isSelected()) {
            Euclidiana.setEnabled(false);
            Cosseno.setEnabled(false);
            Correlacao.setEnabled(false);
        } else {
            Euclidiana.setEnabled(true);
            Cosseno.setEnabled(true);
            Correlacao.setEnabled(true);
        }
    }//GEN-LAST:event_MahalanobisActionPerformed

    private void CorrelacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorrelacaoActionPerformed
        if (Correlacao.isSelected()) {
            Euclidiana.setEnabled(false);
            Cosseno.setEnabled(false);
            Mahalanobis.setEnabled(false);
        } else {
            Euclidiana.setEnabled(true);
            Cosseno.setEnabled(true);
            Mahalanobis.setEnabled(true);
        }
    }//GEN-LAST:event_CorrelacaoActionPerformed

    private void ligaSimplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ligaSimplesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ligaSimplesActionPerformed

    private void ligaCompletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ligaCompletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ligaCompletaActionPerformed

    private void ligaMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ligaMediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ligaMediaActionPerformed

    private void ligaWardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ligaWardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ligaWardActionPerformed

    private void jListResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListResultMouseClicked
        //        if (evt.getClickCount() == 2)
        //        jListResultActionPerformed();
    }//GEN-LAST:event_jListResultMouseClicked

    private void jListResultKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jListResultKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_UP
            || evt.getKeyCode() == KeyEvent.VK_DOWN
            || evt.getKeyCode() == KeyEvent.VK_PAGE_DOWN
            || evt.getKeyCode() == KeyEvent.VK_PAGE_UP
            || evt.getKeyCode() == KeyEvent.VK_END
            || evt.getKeyCode() == KeyEvent.VK_HOME) {
            //            jListResultActionPerformed();
        }
    }//GEN-LAST:event_jListResultKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Correlacao;
    private javax.swing.JRadioButton Cosseno;
    private javax.swing.JRadioButton Euclidiana;
    private javax.swing.JRadioButton Mahalanobis;
    private javax.swing.JPanel Panel_medidas;
    private javax.swing.JButton buttonExecutar;
    private javax.swing.JButton buttonTela;
    private javax.swing.JList jListResult;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneResult;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton ligaCompleta;
    private javax.swing.JRadioButton ligaMedia;
    private javax.swing.JRadioButton ligaSimples;
    private javax.swing.JRadioButton ligaWard;
    // End of variables declaration//GEN-END:variables
}
