/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package moduledefault.clustering.visualization;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Mateus
 */
public class MatrizCorrelacao extends javax.swing.JPanel {
    private double grupos[][];
    /**
     * Creates new form MatrizCorrelacao
     */
    public MatrizCorrelacao() {
        initComponents();
    }

      @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);

        int width = ClusteringFrameVisualization.getFundoDispersão().getWidth();
        int height = ClusteringFrameVisualization.getFundoDispersão().getHeight();
        float w = width / 2;
        float h = height / 2;

        int centroWidth = (int) w;
        int centroHeight = (int) h;

        if (width > height) { //ARRUMAR ESSAS VARIAVEIS GAMBI
            width = height;
        } else {
            height = width;
        }

        int x0 = width - (width - 50);
        int y0 = height - (height - 50);
        int x2 = width - 50;
        int y2 = height - 50;

        g.setColor(Color.black);
        g.drawString("Y", x0 - 10, y0 - 10);
        // g.drawString("2", x2, y0);
        // g.drawString("3", x0, y2);
        g.drawString("X", x2 + 10, y2 + 10);

        //g.drawLine(x0, y0, x2, y0);//1-2
        g.drawLine(x0, y0, x0, y2);//1-3
        //g.drawLine(x2, y0, x2, y2);//2-4
        g.drawLine(x0, y2, x2, y2);//3-4

        int escala = (int) height / 10;
        for (int i = 0; i < height; i++) {
            if (i == escala) {
                g.drawLine(x0 - 5, i, x0 + 5, i);
                escala += escala;
            }
        }
        float m = width / 100;
        int tamPixel = (int) m;
        System.out.println("fezzzzzz\n\n");
        
        if (ClusteringFrameVisualization.getMatrizGrupos() != null) {
            
            g.setColor(Color.black);
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    void setMatrizGrupos(double[][] grupos) {
        this.grupos = grupos;
    }
}
