/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package moduledefault.clustering.view.jpanel;

import java.awt.event.KeyEvent;
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import moduledefault.clustering.kmeans.KMeansPrincipal;
import moduledefault.clustering.uteis.MatrizDados;
import moduledefault.clustering.view.frames.JFrameKmeans;

/**
 *
 * @author Mateus
 */
public class PanelKmeans extends javax.swing.JPanel {

    /**
     * Creates new form panelKmeans
     */
    int numK;
    double[][] matrizDados;
    MatrizDados teste;
    String[] grupos;
    JFrameKmeans frameKmeans;

    public PanelKmeans(double[][] base, String grupos[], JFrameKmeans k) throws IOException {
        initComponents();
        this.matrizDados = base;
        teste = new MatrizDados();
        teste = new MatrizDados();
        this.grupos = grupos;
        startMatrizDados();
        frameKmeans = k;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButtonExecuta = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPaneResult = new javax.swing.JScrollPane();
        jListResult = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxDistancias = new javax.swing.JComboBox();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setPreferredSize(new java.awt.Dimension(718, 458));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jButtonExecuta.setText("Executar");
        jButtonExecuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExecutaActionPerformed(evt);
            }
        });

        jButton2.setText("Limpar Tela");

        jScrollPaneResult.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Resultados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N

        jListResult.setModel(new DefaultListModel());
        jListResult.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListResultMouseClicked(evt);
            }
        });
        jListResult.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jListResultKeyReleased(evt);
            }
        });
        jScrollPaneResult.setViewportView(jListResult);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Distância"));

        jLabel1.setText("Função de Distância:");

        jComboBoxDistancias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Chebyshev","CityBlock","Correlação" ,"Cosseno", "Euclidiana", "Mahalanobis" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxDistancias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxDistancias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(jScrollPaneResult, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExecuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonExecuta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(137, 137, 137)
                .addComponent(jScrollPaneResult, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExecutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExecutaActionPerformed
        int teste_distancia = 0;
        this.jButtonExecuta.setEnabled(false);
        switch (this.jComboBoxDistancias.getSelectedIndex()) {
            case 0:
                JOptionPane.showMessageDialog(null, "Selecione uma Medida de Distância.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                this.jButtonExecuta.setEnabled(true);
                return;
            case 1:
                teste_distancia = 1;
                break;
            case 2:
                teste_distancia = 2;
                break;
            case 3:
                teste_distancia = 3;
                break;
            case 4:
                teste_distancia = 4;
                break;
            case 5:
                teste_distancia = 5;
                break;
            case 6:
                teste_distancia = 6;
                break;
            default:
                break;
        }
        this.numK = frameKmeans.getK();
        boolean paradaAutomatica = frameKmeans.isParadaAutomatica();
        boolean seedAleatorios = frameKmeans.isSeedAleatorios();
        int seeds = 0;
        if(!seedAleatorios){
            seeds = frameKmeans.getSeeds();
        }
        int maxIteracoes = frameKmeans.getMaxIteracoes();
        int iteracoesParada = frameKmeans.getIteracoes();
        KMeansPrincipal k = new KMeansPrincipal(teste, numK,paradaAutomatica,seedAleatorios,seeds,maxIteracoes,iteracoesParada,teste_distancia);
        k.start();
        this.jButtonExecuta.setEnabled(true);
    }//GEN-LAST:event_jButtonExecutaActionPerformed

    private void jListResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListResultMouseClicked
        //        if (evt.getClickCount() == 2)
        //        jListResultActionPerformed();
    }//GEN-LAST:event_jListResultMouseClicked

    private void jListResultKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jListResultKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_UP
                || evt.getKeyCode() == KeyEvent.VK_DOWN
                || evt.getKeyCode() == KeyEvent.VK_PAGE_DOWN
                || evt.getKeyCode() == KeyEvent.VK_PAGE_UP
                || evt.getKeyCode() == KeyEvent.VK_END
                || evt.getKeyCode() == KeyEvent.VK_HOME) {
            //            jListResultActionPerformed();
        }
    }//GEN-LAST:event_jListResultKeyReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonExecuta;
    private static javax.swing.JComboBox jComboBoxDistancias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jListResult;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPaneResult;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables

    public void setMatrizDados(double[][] matrizDados) {
        this.matrizDados = matrizDados;
    }

    public void setGrupos(String[] grupos) {
        this.grupos = grupos;
    }

    public void startMatrizDados() {
        String grupo;
        grupo = grupos[0];
        double[][] base = new double[this.matrizDados.length][this.matrizDados[0].length + 1];
        for (int i = 0; i < this.matrizDados.length; i++) {
            for (int j = 0; j < this.matrizDados[0].length; j++) {
                base[i][j + 1] = this.matrizDados[i][j];
            }
        }

        int contadorGrupos = 1;
        for (int i = 0; i < grupos.length; i++) {
            if (!grupo.equals(grupos[i])) {
                grupo = grupos[i];
                contadorGrupos++;
            }
            base[i][0] = contadorGrupos;
        }


        teste.setColunas(base[0].length);
        teste.setLinhas(base.length);
        teste.setDimensão_matriz();
        teste.setMatriz_dados(base);

        System.out.println("co " + teste.getColunas());
        System.out.println("li " + teste.getLinhas());
        System.out.println("di " + teste.getDimensão_matriz());

        for (int i = 0; i < base.length; i++) {
            for (int j = 0; j < base[0].length; j++) {
                System.out.print(" " + teste.getMatriz_dados()[i][j]);
            }
            System.out.println();
        }
    }
}
