/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package moduledefault.clustering.view.frames;

import java.awt.Point;

/**
 *
 * @author Mateus
 */
public class JFrameSobreKmeans extends javax.swing.JFrame {

    /**
     * Creates new form JFrameSobreKmeans
     */
    public JFrameSobreKmeans(Point _p, int l) {
        initComponents();
        setName("K-means");
        setLocation(_p.x + l + 20, _p.y);
        this.setSize(520, this.getHeight());
        this.jTextArea1.setText("-Parâmetros:\n"
                + "- Número de Clusters: define o número k de clusters\n"
                + "a serem formados pelo algoritmo.\n"
                + "\n"
                + "- Parada Automática: TRUE para parada quando não houver\n"
                + "mudanças dos centróides. FALSE para utilizar parada por\n"
                + "iterações.\n"
                + "\n"
                + "- Parada por Iterações: define o número máximo de iterações\n"
                + "\n"
                + "- Máximo de Iterações: define o número máximo de iterações,\n"
                + "agindo sobre as duas outras condições de parada.\n"
                + "\n"
                + "- Seeds Aleatórios: TRUE para usar os centróides iniciais\n"
                + "aleatórios, FALSE para usar uma porcentagem da base de dados\n"
                + "como centróide inicial (SEEDS)\n"
                + "\n"
                + "- Seeds: porcentagem da base de dados a ser usada para \n"
                + "definição dos centróides iniciais.");
        jTextArea1.setEditable(false);
        jTextArea1.setCaretPosition(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
