/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package moduledefault.clustering.som;

import java.awt.Polygon;
import moduledefault.clustering.som.visualization.FrameSomVisualization;
import moduledefault.clustering.som.visualization.HexGrid;
import moduledefault.clustering.view.jpanel.PanelSOM;

/**
 *
 * @author Thiago M. Faino
 */
public class MarcadoresWaterShed extends javax.swing.JFrame {

    /**
     * Creates new form MarcadoresWaterShed
     */
    int[][] L;
    int cont = 1;

    public MarcadoresWaterShed() {
        initComponents();
        setLocationRelativeTo(null);
        iniciaMatriz();
    }

    public int[][] getL() {
        return L;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new PanelMarcadores();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remover Marcadores");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(525, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(471, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        if(L == null){
            iniciaMatriz();
        }
        int x1 = evt.getX();
        int y1 = evt.getY();

        int NUM_HEX_CORNERS = 6;
        int[] mCornersX = new int[NUM_HEX_CORNERS];
        int[] mCornersY = new int[NUM_HEX_CORNERS];
        HexGrid mCellMetrics = new HexGrid(FrameSomVisualization.getValueU2D());

        boolean aux = false;

        for (int i = 0; i < FrameSomVisualization.getGridMUX(); i++) {
            for (int j = 0; j < FrameSomVisualization.getGridMUY(); j++) {
                mCellMetrics.setCellIndex(i, j);
                mCellMetrics.computeCorners(mCornersX, mCornersY);
                Polygon p = new Polygon(mCornersX, mCornersY, NUM_HEX_CORNERS);
                if (p.contains(x1, y1)) {
                    if (PanelMarcadores.getP().contains(p)) {
                        PanelMarcadores.getP().remove(p);
                    } else {
                        PanelMarcadores.addP(p);
                        L[i][j] = 1;
                    }
                }
            }
        }
        repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!PanelMarcadores.getP().isEmpty()){
            PanelSOM.setMarcadores(L);
        }        
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PanelMarcadores.getP().clear();
        L = null;
        PanelSOM.setMarcadores(L);
        repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public void iniciaMatriz(){
        L = new int[FrameSomVisualization.getGridMUX()][FrameSomVisualization.getGridMUY()];
        for (int i = 0; i < L.length; i++) {
            for (int j = 0; j < L[0].length; j++) {
                L[i][j] = 0;
            }
        }
    }
}
