/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelPreprocess.java
 *
 * Created on 31/08/2010, 15:09:18
 */

package view.jpanel;

import controller.FacadeHost;
import controller.ModuleFactory;
import interfaces.preprocess.ElicitedBasesModuleInterface;
import java.awt.GridBagConstraints;
import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;
import model.ModuleAvailable;

/**
 *
 * @author evaristowb
 */
public class JPanelPreprocess extends javax.swing.JPanel {

    private ElicitedBasesModuleInterface elicitedBasesModuleInterface = null;
    /** Creates new form JPanelPreprocess */

    /**
     * add modules in combobox
     */
    public JPanelPreprocess() {
        initComponents();
        jComboBox.addItem("");
        for(ModuleAvailable<ElicitedBasesModuleInterface> e : ModuleFactory.getArrayListElicitedBasesModules()){
            jComboBox.addItem(e);
        }
    }

    /**
     * action of the combobox
     */
    public void jComboBoxActionPerformed(){
        if(jComboBox.getSelectedItem() instanceof ModuleAvailable){
            try {
                elicitedBasesModuleInterface = ((ModuleAvailable<ElicitedBasesModuleInterface>) jComboBox.getSelectedItem()).getConstructor().newInstance();
                elicitedBasesModuleInterface.setHost(FacadeHost.getHost());
                jPanel.removeAll();
                GridBagConstraints gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 0;
                gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.weightx = 1.0;
                gridBagConstraints.weighty = 1.0;
                jPanel.add(elicitedBasesModuleInterface.getMainPanel(), gridBagConstraints);
                revalidate();
                jPanel.updateUI();
            } catch (InstantiationException ex) {
                Logger.getLogger(JPanelPreprocess.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(JPanelPreprocess.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalArgumentException ex) {
                Logger.getLogger(JPanelPreprocess.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InvocationTargetException ex) {
                Logger.getLogger(JPanelPreprocess.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jPanel.removeAll();
            revalidate();
            jPanel.updateUI();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox = new javax.swing.JComboBox();
        jLabel = new javax.swing.JLabel();
        jPanel = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aquisição de Dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 16))); // NOI18N

        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });

        jLabel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel.setText("Método a ser utilizado:"); // NOI18N

        jPanel.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel)
                        .addGap(487, 487, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        jComboBoxActionPerformed();
    }//GEN-LAST:event_jComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox;
    private javax.swing.JLabel jLabel;
    private javax.swing.JPanel jPanel;
    // End of variables declaration//GEN-END:variables

}
