/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package moduledefault.clustering.visualization;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Mateus
 */
public class MatrizCorrelacao extends javax.swing.JPanel {

    private double grupos[][];

    /**
     * Creates new form MatrizCorrelacao
     */
    public MatrizCorrelacao() {
        initComponents();
    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);

        int width = TecnicasDispersao.getFundoMatrizCorrelacao().getWidth();
        int height = TecnicasDispersao.getFundoMatrizCorrelacao().getHeight();
        float w = width / 2;
        float h = height / 2;

        int x0 = width - (width - 50);
        int y0 = height - (height - 50);
        int inicioX = 0;
        int inicioY = 0;
        if (TecnicasDispersao.getGrupoEscolhidoMatriz() != 0) {
            int tamPixelY = (height - 100) / grupos.length;
            if (this.grupos != null) {
                for (int i = 0; i < grupos.length; i++) {
                    inicioX = 0;
                    for (int j = 0; j < grupos.length; j++) {
                        int x = inicioX;
                        int y = inicioY;
                        if (i == j) {
                            g.setColor(Color.black);
                        } else {
                            if (grupos[i][j] >= -1 && grupos[i][j] < -0.75) {
                                g.setColor(new Color(0, 44, 163));
                            } else if (grupos[i][j] >= -0.75 && grupos[i][j] < -0.5) {
                                g.setColor(new Color(0, 210, 253));
                            } else if (grupos[i][j] >= -0.5 && grupos[i][j] < -0.25) {
                                g.setColor(new Color(1, 202, 132));
                            } else if (grupos[i][j] >= -0.25 && grupos[i][j] < 0) {
                                g.setColor(new Color(0, 186, 39));
                            } else if (grupos[i][j] >= 0 && grupos[i][j] < 0.25) {
                                g.setColor(new Color(1, 180, 162));
                            } else if (grupos[i][j] >= 0.25 && grupos[i][j] < 0.5) {
                                g.setColor(new Color(81, 209, 64));
                            } else if (grupos[i][j] >= 0.5 && grupos[i][j] < 0.75) {
                                g.setColor(new Color(216, 252, 6));
                            } else if (grupos[i][j] >= 0.75 && grupos[i][j] <= 1) {
                                g.setColor(new Color(255, 6, 0));
                            }
                        }
                        g.fillOval(x, y, tamPixelY, tamPixelY);
                        inicioX += tamPixelY;
                    }
                    inicioY += tamPixelY;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(400, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    void setMatrizGrupos(double[][] grupos) {
        this.grupos = grupos;
    }
}
