/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package moduledefault.clustering.view.frames;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import moduledefault.clustering.uteis.ArquivoKmeans;
import moduledefault.clustering.uteis.Arquivos;

/**
 *
 * @author Mateus
 */
public class JFrameKmeans extends javax.swing.JFrame {

    /**
     * Creates new form JFrameKmeans
     */
    int k;
    boolean paradaAutomatica;
    int iteracoes;
    int maxIteracoes;
    boolean seedAleatorios;
    int seeds;

    public JFrameKmeans() {
        initComponents();
        setK(Integer.parseInt(textKClusters.getText()));
        if (comboParadaAutomatica.getSelectedIndex() == 0) {
            setParadaAutomatica(true);
        } else {
            setParadaAutomatica(false);
        }
        setMaxIteracoes(Integer.parseInt(textMaxIteracoes.getText()));
        setIteracoes(Integer.parseInt(textIteracoes.getText()));
        if (comboSeeds.getSelectedIndex() == 0) {
            setSeedAleatorios(true);
        } else {
            setSeedAleatorios(false);
        }
        setSeeds(Integer.parseInt(textSeeds.getText()));
        if (comboParadaAutomatica.getSelectedIndex() == 0) {
            labelParadaIteracoes.setEnabled(false);
            textIteracoes.setEnabled(false);

        } else {
            labelParadaIteracoes.setEnabled(true);
            textIteracoes.setEnabled(true);
        }
        if (comboSeeds.getSelectedIndex() == 0) {
            labelSeeds.setEnabled(false);
            textSeeds.setEnabled(false);
        } else {
            labelSeeds.setEnabled(true);
            textSeeds.setEnabled(true);
        }
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        abrir.setEnabled(true);
        salvar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelParadaIteracoes = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelSeeds = new javax.swing.JLabel();
        textKClusters = new javax.swing.JTextField();
        textMaxIteracoes = new javax.swing.JTextField();
        textSeeds = new javax.swing.JTextField();
        comboParadaAutomatica = new javax.swing.JComboBox();
        textIteracoes = new javax.swing.JTextField();
        comboSeeds = new javax.swing.JComboBox();
        abrir = new javax.swing.JButton();
        salvar = new javax.swing.JButton();
        buttonOK = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "YADMT.Clustering.K-Means"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Sobre"));

        jLabel3.setText("Algoritmo de Agrupamento de Dados k-means");

        jButton1.setText("Sobre");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Configurações"));

        jLabel1.setText("Número de Clusters");

        jLabel2.setText("Parada Automática:");

        labelParadaIteracoes.setText("Parada por Iterações:");

        jLabel4.setText("Máximo de Iterações:");

        jLabel5.setText("Seeds Aleatórios:");

        labelSeeds.setText("Seeds:");

        textKClusters.setText("3");

        textMaxIteracoes.setText("100");

        textSeeds.setText("10");
        textSeeds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSeedsActionPerformed(evt);
            }
        });

        comboParadaAutomatica.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TRUE", "FALSE" }));
        comboParadaAutomatica.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                comboParadaAutomaticaMouseWheelMoved(evt);
            }
        });
        comboParadaAutomatica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboParadaAutomaticaActionPerformed(evt);
            }
        });

        textIteracoes.setText("100");
        textIteracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIteracoesActionPerformed(evt);
            }
        });

        comboSeeds.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TRUE", "FALSE" }));
        comboSeeds.setSelectedIndex(1);
        comboSeeds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSeedsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelSeeds)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(labelParadaIteracoes)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textKClusters)
                    .addComponent(textMaxIteracoes)
                    .addComponent(textSeeds)
                    .addComponent(comboParadaAutomatica, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textIteracoes)
                    .addComponent(comboSeeds, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textKClusters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboParadaAutomatica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelParadaIteracoes)
                    .addComponent(textIteracoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textMaxIteracoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboSeeds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSeeds)
                    .addComponent(textSeeds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        abrir.setText("Abrir");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });

        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        buttonOK.setText("OK");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(abrir, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abrir)
                    .addComponent(salvar)
                    .addComponent(buttonOK)
                    .addComponent(buttonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textSeedsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSeedsActionPerformed
    }//GEN-LAST:event_textSeedsActionPerformed

    private void comboParadaAutomaticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboParadaAutomaticaActionPerformed
        if (comboParadaAutomatica.getSelectedIndex() == 0) {
            labelParadaIteracoes.setEnabled(false);
            textIteracoes.setEnabled(false);

        } else {
            labelParadaIteracoes.setEnabled(true);
            textIteracoes.setEnabled(true);
        }
    }//GEN-LAST:event_comboParadaAutomaticaActionPerformed

    private void comboSeedsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSeedsActionPerformed
        if (comboSeeds.getSelectedIndex() == 0) {
            labelSeeds.setEnabled(false);
            textSeeds.setEnabled(false);
        } else {
            labelSeeds.setEnabled(true);
            textSeeds.setEnabled(true);
        }
    }//GEN-LAST:event_comboSeedsActionPerformed

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        setValores();
    }//GEN-LAST:event_buttonOKActionPerformed

    private void comboParadaAutomaticaMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_comboParadaAutomaticaMouseWheelMoved
    }//GEN-LAST:event_comboParadaAutomaticaMouseWheelMoved

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFrameSobreKmeans jf = new JFrameSobreKmeans(this.getLocation(), this.getWidth());
        jf.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textIteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIteracoesActionPerformed

    }//GEN-LAST:event_textIteracoesActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        setValores();
        ArquivoKmeans aK = new ArquivoKmeans(k, paradaAutomatica, iteracoes, maxIteracoes, seedAleatorios, seeds);
        Arquivos fileK = new Arquivos();
        fileK.salvarKmeans(aK);
    }//GEN-LAST:event_salvarActionPerformed

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed

        Arquivos fileK = new Arquivos();
        try {
            ArquivoKmeans aK = fileK.abrirKmeans();
            setK(aK.getK());
            setIteracoes(aK.getIteracoes());
            setMaxIteracoes(aK.getMaxIteracoes());
            setSeeds(aK.getSeeds());
            setParadaAutomatica(aK.isParadaAutomatica());
            setSeedAleatorios(aK.isSeedAleatorios());
            this.textIteracoes.setText(String.valueOf(getIteracoes()));
            this.textKClusters.setText(String.valueOf(getK()));
            this.textMaxIteracoes.setText(String.valueOf(getMaxIteracoes()));
            this.textSeeds.setText(String.valueOf(getSeeds()));
            if (isParadaAutomatica()) {
                this.comboParadaAutomatica.setSelectedIndex(0);
                labelParadaIteracoes.setEnabled(false);
                textIteracoes.setEnabled(false);
            } else {
                this.comboParadaAutomatica.setSelectedIndex(1);
                labelParadaIteracoes.setEnabled(true);
                textIteracoes.setEnabled(true);
            }
            if (isSeedAleatorios()) {
                this.comboSeeds.setSelectedIndex(1);
                labelSeeds.setEnabled(true);
                textSeeds.setEnabled(true);
            } else {
                this.comboSeeds.setSelectedIndex(0);
                labelSeeds.setEnabled(false);
                textSeeds.setEnabled(false);
            }
        } catch (IOException ex) {
            Logger.getLogger(JFrameKmeans.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_abrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameKmeans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameKmeans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameKmeans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameKmeans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameKmeans().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrir;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonOK;
    private javax.swing.JComboBox comboParadaAutomatica;
    private javax.swing.JComboBox comboSeeds;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelParadaIteracoes;
    private javax.swing.JLabel labelSeeds;
    private javax.swing.JButton salvar;
    private javax.swing.JTextField textIteracoes;
    private javax.swing.JTextField textKClusters;
    private javax.swing.JTextField textMaxIteracoes;
    private javax.swing.JTextField textSeeds;
    // End of variables declaration//GEN-END:variables

    public int getK() {
        return k;
    }

    public void setK(int k) {
        this.k = k;
    }

    public boolean isParadaAutomatica() {
        return paradaAutomatica;
    }

    public void setParadaAutomatica(boolean paradaAutomatica) {
        this.paradaAutomatica = paradaAutomatica;
    }

    public int getIteracoes() {
        return iteracoes;
    }

    public void setIteracoes(int iteracoes) {
        this.iteracoes = iteracoes;
    }

    public int getMaxIteracoes() {
        return maxIteracoes;
    }

    public void setMaxIteracoes(int maxIteracoes) {
        this.maxIteracoes = maxIteracoes;
    }

    public boolean isSeedAleatorios() {
        return seedAleatorios;
    }

    public void setSeedAleatorios(boolean seedAleatorios) {
        this.seedAleatorios = seedAleatorios;
    }

    public int getSeeds() {
        return seeds;
    }

    public void setSeeds(int seeds) {
        this.seeds = seeds;
    }

    private void setValores() {
        setK(Integer.parseInt(textKClusters.getText()));
        if (comboParadaAutomatica.getSelectedIndex() == 0) {
            setParadaAutomatica(true);
        } else {
            setParadaAutomatica(false);
        }
        setMaxIteracoes(Integer.parseInt(textMaxIteracoes.getText()));
        setIteracoes(Integer.parseInt(textIteracoes.getText()));
        if (comboSeeds.getSelectedIndex() == 0) {
            setSeedAleatorios(true);
        } else {
            setSeedAleatorios(false);
        }
        setSeeds(Integer.parseInt(textSeeds.getText()));
        this.setVisible(false);
    }
}
